apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: holiday-songs
  description: The place to be, for great holiday songs
spec:
  type: service
  lifecycle: production
  owner: team-a
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - artist-api
