apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: holiday-songs
  description: The place to be, for holiday songs
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - artist-api
