apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web1
  description: The place to be, for great artists
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: artists-db1
  description: Stores artist details
spec:
  type: database
  owner: artist-relations-team
  system: artist-engagement-portal
